### ISSUE TITLE
5.3里面有点小问题

### ISSUE THREAD

**Issue by addelete** [apollopy/flysystem-aliyun-oss#2]
5.3里面好像要用下面的方法上传
Storage::disk('oss')->putFile($path,$file); //第一个参数是上传目录，第二个参数是UploadedFile对象

**Comment by apollopy** [comment]
Storage::disk('oss')->putFile($path, '/local_file_path/1.png', ['mimetype' => 'image/png']);

README.md 里写的不就是这样吗？第一个参数是上传目录，第二个参数是需要上传的文件路径。

**Comment by apollopy** [comment]
putFile 是扩展方法，应该是 laravel 5.1 还是 5.3 没关系。

到底是哪种情况下没法上传？请给个详细的例子。

**Comment by apollopy** [comment]
我明白你意思了，5.3 laravel 添加了 Storage::putFile 方法。覆盖了以前`Illuminate\Filesystem\ FilesystemAdapter` __call 的调用。但实际执行代码是不一样的。

如果你在 5.3 下要用原来扩展里的 putFile，可以尝试 Storage::disk('oss')->getDriver()->putFile()

我这边业务还没升到 5.3，没测试过。

**Comment by apollopy** [comment]
@addelete 这是否能解决你的问题？

**Comment by addelete** [comment]
忘记关闭了 抱歉
