### ISSUE TITLE
获取文件目录的时候如果不加 ‘/’ 会没有结果。 

### ISSUE THREAD

**Issue by mahaidong** [apollopy/flysystem-aliyun-oss#3]
$directories = Storage::directories($path);
没有结果。

**Comment by apollopy** [comment]
我在 master 分支更新了一下，你可以先试试。如果没问题请回复我，我再打 tag。
不过 oss 获取目录下所有文件和目录下所有子目录的性能很差，生产环境建议尽量避免。

**Comment by mahaidong** [comment]
感谢你这么快回复 ：）, 测试了一些。 没有问题

**Comment by apollopy** [comment]
好的，如果有别的问题希望及时同步。
