### ISSUE TITLE
获取url的时候提示 This driver does not support retrieving URLs

### ISSUE THREAD

**Issue by lepig** [apollopy/flysystem-aliyun-oss#7]
上传成功后我使用`Storage::file('xxx')`调用的时候返回如下错误
![qq 20181204162346](https://user-images.githubusercontent.com/5689279/49428556-588ae500-f7e1-11e8-9972-851a5f0195b1.png)

**Comment by lepig** [comment]
代码 如下

![qq 20181204162447](https://user-images.githubusercontent.com/5689279/49428692-b0295080-f7e1-11e8-91b7-5a97080ed950.png)

**Comment by apollopy** [comment]
我没有太看懂你的意图，你是想干嘛？

**Comment by apollopy** [comment]
你用的是 laravel 5.3 吧？目前我自己的项目用的是 5.2，所以没很好的支持 laravel 的 url 方法。你可以先使用 SignedDownloadUrl。

**Comment by lepig** [comment]
@apollopy 我用的是5.5。我是想上传后获取图片的地址。比如修改头像后，存到数据库。然后想拿到完整的地址，类似`http://bucket.oss.com/avatar.png`

我是`Storage::url('avatar.png')`报了这个错。

**Comment by apollopy** [comment]
> @apollopy 我用的是5.5。我是想上传后获取图片的地址。比如修改头像后，存到数据库。然后想拿到完整的地址，类似`http://bucket.oss.com/avatar.png`
> 
> 我是`Storage::url('avatar.png')`报了这个错。

laravel 从 5.3 开始支持 Storage::url 的，我这边项目还是 5.2 呢……我自己项目里，因为类似头像地址这样的需求，我是存 CDN 的地址，而不是 OSS 的地址的，所以就没急着加这个……

**Comment by apollopy** [comment]
> @apollopy 我用的是5.5。我是想上传后获取图片的地址。比如修改头像后，存到数据库。然后想拿到完整的地址，类似`http://bucket.oss.com/avatar.png`
> 
> 我是`Storage::url('avatar.png')`报了这个错。

后续会加……

**Comment by lepig** [comment]
@apollopy  好的 谢谢。那我自己处理一下。
