### ISSUE TITLE
文件上传 Driver is not supported.错误

### ISSUE THREAD

**Issue by 734380794** [apollopy/flysystem-aliyun-oss#9]
![image](https://user-images.githubusercontent.com/18534797/84483359-d2036d80-accb-11ea-930d-04aec3713ed0.png)
按照文档流程操作，出现这个错误，配置检查无误，帮忙解答一下。

**Comment by apollopy** [comment]
能给我一个能干净能复现的 demo 吗？

**Comment by 734380794** [comment]
`<?php

namespace App\Http\Controllers\Admin\Common;
use App\Http\Controllers\BaseController;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class UploadFileController extends BaseController
{
    public function uploadFile(Request $request)
    {
        $file = $this->request->file('file');
        $extend = $file->getClientOriginalExtension();
        $path = $file->getRealPath();
        $srcName = sprintf('%s.%s', time(), $extend);
        Storage::disk('oss')->put($srcName, file_get_contents($path));
        }
    }
}`

**Comment by 734380794** [comment]
Driver [] is not supported.

**Comment by 734380794** [comment]
问题已经解决，laravel-admin扩展，修改config/admin.php disk 配置，与filesystems.php disk 配置保持一致

**Comment by apollopy** [comment]
收到
